image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./src/api-ci/rest/artifacts/app-mbank.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info